### ISSUE TITLE
Rekado crashes on launch

### ISSUE THREAD

**Issue by neogohan324** [MenosGrante/Rekado#33]
Maybe this is unique to me, but Rekado crashes immediately upon launch. This is true of v2.4 and above. However, v2.3 and below work fine.

I'm using a Verizon Google Pixel on the latest Android and security updates (Android 9, December 9th update). I'm not rooted, nor is my bootloader even unlocked. This error also occurred on earlier versions of the OS prior to 2.5.2's release.

I've tried uninstalling completely (clear the app's cache, clear the app's data, uninstall the app) before reinstalling, but that doesn't fix it. I've also made sure to go into "App info" and enable storage permissions since the app crashes before it can request them. Not sure what else to check or where any logs may be stored that could be useful.

**Comment by MenosGrante** [comment]
@neogohan324 sorry for late response. I am sure, that without root you can't get any system logs. Could you try one more time uninstall Rekado and remove Rekado folder in root of your file system?

**Comment by MenosGrante** [comment]
Which payloads have you used?

**Comment by neogohan324** [comment]
Just ReiNX -- all versions at some point except for 1.7.1.

**Comment by MenosGrante** [comment]
Should be resolved in 2.6 update.

**Comment by neogohan324** [comment]
Strangely, 2.6 has reintroduced the issue. After upgrading from 2.5.2 to 2.6, Rekado now once again crashes on launch. If I revert to 2.5.2, the application starts without issue.

My only payload is ReiNX 2.0. Removing it and upgrading to 2.6 again doesn't resolve the issue -- still hard-crashes on launch. I assume that repeating the steps of wiping the cache and storage will resolve it, but let me know if there are some tests or diagnostics I can provide, since once I 'fix' the issue, I can't seem to replicate it.

Or let me know if this should just be dropped and tagged as "your phone is just weird, man".

**Comment by pinn73** [comment]
same issue here on s8+ 9.0. Cleared cache/ data and works

**Comment by 5H00T4** [comment]
And same on a Pixel 2 when going from v2.5 to 2.6.
Clearing data and cache solves the issue.
Maybe just add a comment to the release page for now.
Not a huge issue by any means, but I was thoroughly confused.

**Comment by MenosGrante** [comment]
Well, I will retest this issue one more time.

**Comment by DavidOliM** [comment]
I had the same issue here. I went to the app info and allowed storage access manually and it opened normally

**Comment by MenosGrante** [comment]
Guys, I have just released another update - 2.6.1, which should fix this annoying issue. Could you retest this please?

**Comment by neogohan324** [comment]
Unfortunately, it does not. I updated to 2.6.1 from 2.6 and when that didn't work, I uninstalled and installed it 'fresh'. Still crashes on launch. I have not cleared the cache or storage.

I also tried reverting to 2.5.2 then updating to 2.6.1. And while 2.5.2 still works fine, it crashes once again after the update to 2.6.1.

If there are any steps I can do to help troubleshoot, let me know.

**Comment by MenosGrante** [comment]
Oh, try to uninstall application and remove Rekado folder from root of your storage. Then install as always.

**Comment by neogohan324** [comment]
Uninstalled then deleted the "Rekado" folder at the root of storage. Reinstalled 2.6.1, and it still crashes at launch.

Note that I didn't use Androids "clear cache" or "clear storage" functions. Just manually deleted the folder.

**Comment by MenosGrante** [comment]
Well, I will revert 2.6.1 update for now, thank you!

**Comment by sruggier** [comment]
I updated from 2.5.1 to 2.6.1 and found that Rekado started crashing on startup after that. I reproduced the issue with logcat running and found this:

```
02-25 22:41:58.184  2378  2399 I ActivityManager: Start proc 11441:com.pavelrekun.rekado/u0a168 for activity com.pavelrekun.rekado/.screens.main_activity.MainActivity
02-25 22:41:58.449 11441 11441 D AndroidRuntime: Shutting down VM
02-25 22:41:58.450 11441 11441 E AndroidRuntime: FATAL EXCEPTION: main
02-25 22:41:58.450 11441 11441 E AndroidRuntime: Process: com.pavelrekun.rekado, PID: 11441
02-25 22:41:58.450 11441 11441 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.pavelrekun.rekado.RekadoApplication: java.lang.IllegalArgumentException: Theme with 'Castro' does not exist!
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Theme with 'Castro' does not exist!
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.pavelrekun.siga.data.Theme$Companion.findById(Theme.kt:28)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.pavelrekun.siga.services.Siga.initValues(Siga.kt:43)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.pavelrekun.siga.services.Siga.init(Siga.kt:32)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.pavelrekun.rekado.RekadoApplication.configureThemeEngine(RekadoApplication.kt:34)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at com.pavelrekun.rekado.RekadoApplication.onCreate(RekadoApplication.kt:29)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
02-25 22:41:58.450 11441 11441 E AndroidRuntime: 	... 8 more
```

Clearing cache didn't resolve the issue, but it started working after I cleared all of the application's data.

**Comment by MenosGrante** [comment]
@sruggier Wow, that will help me a lot! I was fixing the wrong side then :D

**Comment by MenosGrante** [comment]
I have made some changes for intialization process for 2.6.1 and its available now again, but crash will probably persist for pre-2.6.1 versions. Should not occur in future releases.

**Comment by kuroyukihime0** [comment]
2.6.1 also crash on my mi6 android 8.0.
Here is the log，thx

`java.lang.RuntimeException: Unable to create application com.pavelrekun.rekado.RekadoApplication: kotlin.UninitializedPropertyAccessException: lateinit property defaultSetup has not been initialized
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5884)
 at android.app.ActivityThread.-wrap1(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6701)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property defaultSetup has not been initialized
 at com.pavelrekun.siga.services.Siga.defaults(Siga.kt:64)
 at com.pavelrekun.rekado.RekadoApplication.configureThemeEngine(RekadoApplication.kt:33)
 at com.pavelrekun.rekado.RekadoApplication.onCreate(RekadoApplication.kt:29)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5881)
 ... 8 more`

**Comment by kuroyukihime0** [comment]
it also appears on my og Pixel 9.0,but after downgrading to 2.6,it works
it seems that some changes on submodule 'siga' casue that

**Comment by MenosGrante** [comment]
Oh, new day - new crash. Will fix it now.

**Comment by n0101** [comment]
Just to add, I  experience the same crash and same logcat error that kuro does on my pixel 2 xl 9.0 stock ROM, latest build.  I am using a custom kernel and magisk but I don't think either would contribute to this.

**Comment by Cuphat** [comment]
I have a Pixel 2 XL and just installed Rekado for the first time (2.6.1) and it immediately crashes for me as well. Stock, unrooted Android 9.

**Comment by mackybean** [comment]
I have a Samsung Galaxy S9+ stock, unrooted on Android 9.0, and every version past 2.5.2 crashes upon launch for me.

**Comment by RussKay** [comment]
I posted in the other thread. Just posting here so others can see. Verizon Pixel 3, Android 9 Feb 5 updates. All stock. No modifications. 2.6 runs great. 2.6.1 crashes on launch. I also always do a clean install. I had issues with an older release and since then, anytime I upgraded rekado, it crashed on launch. If I removed the older version and the rekado folder first, then the new version would work. However, 2.6.1 crashes on launch no matter if it's a clean install or an upgrade.

**Comment by MenosGrante** [comment]
Looking at the logs I assume it will crash on every device :)

**Comment by MenosGrante** [comment]
I have pushed one more 2.6.1 build, that should fix all of this crashes, but it will probably persist for pre-2.6.1 versions. Should not occur in future releases.

**Comment by neogohan324** [comment]
All fixed here! It now installs and loads without issue. :)

**Comment by MenosGrante** [comment]
Yeah, I was debugging this build for a while, so should be fully stable now :)
